#define PMZM_WPNNAME_THERMOMETER_UPGRADED_FLAME "pmzm_thermometer_upgraded"
#define PMZM_WPNNAME_THERMOMETER_UPGRADED_ICE "pmzm_thermometer_upgraded_alt"

#define PMZM_ZVAR_THERMOMETER_UPGRADED_ICE_CYLINDER_RADIUS "pmzm_icegun_cylinder_radius"
#define PMZM_ZVAR_THERMOMETER_UPGRADED_ICE_RANGE "pmzm_icegun_range"
#define PMZM_ZVAR_THERMOMETER_UPGRADED_ICE_DAMAGE "pmzm_icegun_damage"

#define PMZM_EFF_THERMOMETER_UPGRADED_ICE_SMOKE_CLOUD "pmzm_icegun_smoke_cloud"
#define PMZM_EFF_THERMOMETER_UPGRADED_ICE_GROW "pmzm_icegun_grow"
#define PMZM_EFF_THERMOMETER_UPGRADED_ICE_SHATTER "pmzm_icegun_shatter"

#define PMZM_THERMOMETER_UPGRADED_ICE_SLOWDOWN_RATE 0.5
#define PMZM_THERMOMETER_UPGRADED_ICE_SLOWDOWN_DURATION 10.0

#define PMZM_THERMOMETER_UPGRADED_NOTIFY_ICE_THAWED "ice_block_thawed"

#define PMZM_THERMOMETER_UPGRADED_ICE_TAG "J_SpineLower"
