#define PMZM_TEMPERATURE_UPDATE_PERIOD 1.0
#define PMZM_TEMPERATURE_FIELD_BITS 8
#define PMZM_TEMPERATURE_MIN -5.0
#define PMZM_TEMPERATURE_STEP 0.1

#define PMZM_EFF_TEMPERATURE_COLD_BREATH_1P "pmzm_player_cold_breath_1p"

#define PMZM_TEMPERATURE_NOTIFY_STOP_BREATH "stop_player_breath"

#define PMZM_TEMPERATURE_CLIENTFIELD_ISFREEZING "temperature_isfreezing"
#define PMZM_TEMPERATURE_CLIENTFIELD_UIMODEL_CELSIUS "hudItems.pmzmThermometerUpgraded.celsius"
